import Link from 'next/link'
import { Bot, AlertTriangle, ExternalLink } from 'lucide-react'

interface AIDisclosureProps {
  /**
   * Whether to show the compact version (inline badge) or full version (card)
   */
  variant?: 'compact' | 'full'
  /**
   * Additional CSS classes
   */
  className?: string
}

/**
 * AI-Generated Content Disclosure
 *
 * Required for transparency and legal compliance. Informs users that
 * resort guide content is generated using AI and may contain errors.
 *
 * Two variants:
 * - compact: Small inline badge for headers/sidebars
 * - full: Detailed card for page footers with full disclaimer
 */
export function AIDisclosure({ variant = 'full', className = '' }: AIDisclosureProps) {
  if (variant === 'compact') {
    return (
      <div className={`inline-flex items-center gap-1.5 px-3 py-1.5 bg-gold-50 border border-gold-200 rounded-full text-xs text-gold-700 ${className}`}>
        <Bot className="w-3.5 h-3.5" />
        <span className="font-medium">AI-Generated Guide</span>
      </div>
    )
  }

  return (
    <div className={`bg-gradient-to-br from-gold-50 to-dark-50 rounded-2xl p-6 border border-gold-200 ${className}`}>
      <div className="flex items-start gap-4">
        <div className="p-2.5 rounded-xl bg-gold-100 flex-shrink-0">
          <Bot className="w-5 h-5 text-gold-600" />
        </div>
        <div className="flex-1">
          <h3 className="font-display font-semibold text-dark-800 mb-2 flex items-center gap-2">
            AI-Generated Content
            <AlertTriangle className="w-4 h-4 text-gold-500" />
          </h3>
          <p className="text-sm text-dark-600 leading-relaxed mb-3">
            This resort guide was created using AI technology. While we strive for accuracy,
            information may be outdated or contain errors. <strong>Always verify prices,
            availability, and facilities directly with the resort before booking.</strong>
          </p>
          <div className="flex flex-wrap gap-3 text-xs">
            <Link
              href="/terms#ai-content"
              className="inline-flex items-center gap-1 text-gold-600 hover:text-gold-700 font-medium"
            >
              Learn more
              <ExternalLink className="w-3 h-3" />
            </Link>
            <span className="text-dark-400">|</span>
            <span className="text-dark-500">
              Last updated: {new Date().toLocaleDateString('en-US', { month: 'short', year: 'numeric' })}
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}

/**
 * AI Disclaimer for page footers
 *
 * Shorter, inline version suitable for footer areas
 */
export function AIDisclaimerFooter({ className = '' }: { className?: string }) {
  return (
    <p className={`text-xs text-dark-400 ${className}`}>
      <Bot className="w-3.5 h-3.5 inline-block mr-1 -mt-0.5" />
      Content generated by AI. Prices and availability are estimates only.{' '}
      <Link href="/terms" className="underline hover:text-dark-500">
        See terms
      </Link>
      .
    </p>
  )
}
