import { NextRequest, NextResponse } from 'next/server'
import { createClient, SupabaseClient } from '@supabase/supabase-js'

// Lazy initialization to avoid build-time errors
let _supabaseAdmin: SupabaseClient | null = null

function getSupabaseAdmin(): SupabaseClient {
  if (!_supabaseAdmin) {
    const url = process.env.NEXT_PUBLIC_SUPABASE_URL
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY

    if (!url || !key) {
      throw new Error('Missing Supabase configuration')
    }

    _supabaseAdmin = createClient(url, key)
  }
  return _supabaseAdmin
}

interface SubscribeRequest {
  email: string
  name?: string
  source?: string
  source_detail?: string
  referral_code?: string
}

// Rate limiting: simple in-memory store (resets on deploy)
const rateLimitStore = new Map<string, { count: number; resetAt: number }>()
const RATE_LIMIT_WINDOW_MS = 60 * 1000 // 1 minute
const RATE_LIMIT_MAX_REQUESTS = 5

function isRateLimited(ip: string): boolean {
  const now = Date.now()
  const record = rateLimitStore.get(ip)

  if (!record || now > record.resetAt) {
    rateLimitStore.set(ip, { count: 1, resetAt: now + RATE_LIMIT_WINDOW_MS })
    return false
  }

  if (record.count >= RATE_LIMIT_MAX_REQUESTS) {
    return true
  }

  record.count++
  return false
}

export async function POST(request: NextRequest) {
  try {
    // Rate limiting
    const ip = request.headers.get('x-forwarded-for')?.split(',')[0] || 'unknown'
    if (isRateLimited(ip)) {
      return NextResponse.json(
        { error: 'Too many requests. Please try again later.' },
        { status: 429 }
      )
    }

    // Parse request body
    const body: SubscribeRequest = await request.json()
    const { email, name, source = 'website', source_detail, referral_code } = body

    // Validate email
    if (!email || typeof email !== 'string') {
      return NextResponse.json(
        { error: 'Email is required' },
        { status: 400 }
      )
    }

    // Basic email validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      )
    }

    const supabase = getSupabaseAdmin()

    // Check for existing subscriber
    const { data: existing } = await supabase
      .from('subscribers')
      .select('id, status')
      .eq('email', email.toLowerCase().trim())
      .single()

    if (existing) {
      // If previously unsubscribed, reactivate
      if (existing.status === 'unsubscribed') {
        const { error: updateError } = await supabase
          .from('subscribers')
          .update({
            status: 'active',
            unsubscribed_at: null,
            updated_at: new Date().toISOString(),
          })
          .eq('id', existing.id)

        if (updateError) {
          console.error('Reactivation error:', updateError)
          return NextResponse.json(
            { error: 'Failed to reactivate subscription' },
            { status: 500 }
          )
        }

        return NextResponse.json({
          success: true,
          message: 'Welcome back! Your subscription has been reactivated.',
          reactivated: true,
        })
      }

      // Already subscribed and active
      return NextResponse.json({
        success: true,
        message: "You're already subscribed!",
        existing: true,
      })
    }

    // Look up referrer if referral code provided
    let referredBy: string | null = null
    if (referral_code) {
      const { data: referrer } = await supabase
        .from('subscribers')
        .select('id')
        .eq('referral_code', referral_code.toLowerCase().trim())
        .single()

      if (referrer) {
        referredBy = referrer.id
      }
    }

    // Insert new subscriber
    const { data: newSubscriber, error: insertError } = await supabase
      .from('subscribers')
      .insert({
        email: email.toLowerCase().trim(),
        name: name?.trim() || null,
        source,
        source_detail: source_detail || request.headers.get('referer'),
        referred_by: referredBy,
        status: 'active',
        // Note: referral_code is auto-generated by trigger
      })
      .select('id, referral_code')
      .single()

    if (insertError) {
      console.error('Insert error:', insertError)
      return NextResponse.json(
        { error: 'Failed to subscribe. Please try again.' },
        { status: 500 }
      )
    }

    // Trigger welcome sequence
    // Look up the welcome sequence and start the subscriber on it
    const { data: welcomeSequence } = await supabase
      .from('email_sequences')
      .select('id')
      .eq('name', 'welcome')
      .eq('status', 'active')
      .single()

    if (welcomeSequence) {
      // Start subscriber on the welcome sequence
      // Set next_send_at to now for immediate processing by cron
      const { error: sequenceError } = await supabase
        .from('subscriber_sequence_progress')
        .insert({
          subscriber_id: newSubscriber.id,
          sequence_id: welcomeSequence.id,
          current_step: 0,
          started_at: new Date().toISOString(),
          next_send_at: new Date().toISOString(), // Ready for immediate send
          status: 'active',
        })

      if (sequenceError) {
        // Log but don't fail the signup - sequence can be triggered later
        console.error('Failed to start welcome sequence:', sequenceError)
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Welcome to Snowthere! Check your inbox for your free checklist.',
      subscriber_id: newSubscriber.id,
      referral_code: newSubscriber.referral_code,
    })
  } catch (error) {
    console.error('Subscribe error:', error)
    return NextResponse.json(
      { error: 'An unexpected error occurred' },
      { status: 500 }
    )
  }
}

// Health check / preflight
export async function GET() {
  return NextResponse.json({ status: 'ok', endpoint: 'subscribe' })
}
