-- Country-level content for index pages (e.g., /resorts/austria)
-- Generated by pipeline, rendered on country pages to avoid thin content
CREATE TABLE IF NOT EXISTS country_content (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    country TEXT NOT NULL UNIQUE,
    intro_text TEXT,
    resort_count INTEGER DEFAULT 0,
    avg_daily_cost NUMERIC(10,2),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for lookups by country name
CREATE INDEX IF NOT EXISTS idx_country_content_country ON country_content(country);

-- Row Level Security
ALTER TABLE country_content ENABLE ROW LEVEL SECURITY;

-- Public read access (anon key can SELECT)
CREATE POLICY "Public can read country_content"
  ON country_content FOR SELECT TO anon
  USING (true);

-- Service role manages writes (pipeline uses service key)
CREATE POLICY "Service role manages country_content"
  ON country_content FOR ALL TO service_role
  USING (true) WITH CHECK (true);
